@startuml relations_acteurs
skinparam componentStyle rectangle

frame "ENS" {
	[Ressource(s) sémantique(s)] as rs_ens
	[Système d'Information] as si_ens
	[Catalogue de ressources sémantiques] as cat_ens
}

frame "SMT" {
	[Ressource(s) sémantique(s)] as rs_smt
}

frame "Utilisateur1" {
	[Instance logicielle 1] as inst1
}

frame "Utilisateur2" {
	[Instance logicielle 2] as inst2
}

frame "Utilisateur3" {
	[Instance logicielle 3] as inst3
}

rs_ens --> cat_ens : "0..*"
rs_smt --> cat_ens : "0..*"
cat_ens --> si_ens : "1..*"
si_ens --> inst1
si_ens --> inst2
si_ens --> inst3
@enduml